# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d4778130920ce786028ca0059cbf57fcbada3c3e817bc9a570de91543aef30db2bb4df11e221ef0242f03fa60b745ba3b967757c454e77a2fdbf49777445d49

test:
  secret_key_base: d3d7a293396730fd75a7acda55e9c196d787fb0767e7b00729d82265eda04f16243916a7f3a7da847ae1b57b1b2591e610d476ffb7cbd715ed5123221f49157c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
